service: ghostscript-service

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-2'}
  stage: ${opt:stage, 'prod'}

layers:
  ghostscript-aws-lambda-layer:
    path: build
    name: ghostscript-aws-lambda-layer
    description: Ghostscript v9.54.0 (/opt/bin/gs)
    licenseInfo: AGPL-3.0
    retain: true
